nice-digital/niceorg-client

- package-lock.json
- package.json
- pages/guidance/index.html
- src/components/__components.scss
- src/components/_footer.scss
- src/components/_hero.scss
- src/components/_to-top.scss
- src/nice.bootstrap/_layout.scss
- src/nice.bootstrap/_media-stack.scss
https://nicedigital.atlassian.net/browse/NOC-7
See also https://github.com/nhsevidence/nice-design-system/pull/40
> NOC-7 Find guidance page (was JM-87)

- src/app.scss
https://nicedigital.atlassian.net/browse/NOC-8
Beta css removed
> NOC-8 Release new design of the topic page

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-9
> NOC-9 package updates

- package-lock.json
- package.json
[https://nicedigital.atlassian.net/browse/NOC-14](https://nicedigital.atlassian.net/browse/NOC-14)
> NOC-14 Updated package.json to use latest NDS

- src/components/__components.scss
- src/components/_blockquote.scss
- src/components/_comments-form.scss
- src/components/_embed-responsive.scss
- src/components/_footer.scss
- src/components/_news-content.scss
- src/components/_share-links.scss
- src/layout/_container.scss
- src/nice.bootstrap/__bootstrap.scss
- src/nice.bootstrap/_grid.scss
- src/nice.bootstrap/_hero-unit.scss
- src/nice.bootstrap/_media-object.scss
- src/nice.bootstrap/_media.scss
- src/nice.bootstrap/_pager.scss
- src/nice.bootstrap/_thumbnail.scss
- src/nice.bootstrap/navigation/_navbar-corporate.scss
https://nicedigital.atlassian.net/browse/NW-1140
> NW-1140 External comms/news pages

- src/components/_news-content.scss
- src/nice.bootstrap/_layout.scss
https://nicedigital.atlassian.net/browse/NOC-16
> NOC-16 Fixes for news pages on mobile

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-19
> NOC-19 Update package @nice-digital/design-system

- src/nice.bootstrap/_hero-unit.scss
https://nicedigital.atlassian.net/browse/NOC-18
> NOC-18 News homepage heading

- README.md
- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-31
> NOC-31 Update NDS version

- pages/about/what-we-do/life-sciences/scientific-advice/eunethta-multi-hta-advice/index.html
- pages/about/what-we-do/life-sciences/scientific-advice/express-scientific-advice/index.html
- pages/about/what-we-do/life-sciences/scientific-advice/index.html
- pages/index.html
- src/components/__components.scss
- src/components/_timeline.scss
- src/nice.bootstrap/_alert.scss
https://nicedigital.atlassian.net/browse/NOC-21
> NOC-21 Timeline styling

- pages/tables/smorgasbord.html
- src/nice.bootstrap/__bootstrap.scss
- src/nice.bootstrap/_tables.scss
https://nicedigital.atlassian.net/browse/NOC-4
> NOC-4 Table styling

- .prettierignore
- pages/forms-bootstrap.html
- pages/forms.html
- pages/forms/smorgasbord.html
- pages/get-involved/stakeholder-registration/register/index.html
- src/components/__components.scss
- src/components/_forms.scss
- src/nice.bootstrap/_forms.scss
https://nicedigital.atlassian.net/browse/NOC-3
> NOC-3 Form styling

- src/components/_print.scss
- This is to make the grid honour page-break rules
https://nicedigital.atlassian.net/browse/NOC-33
> NOC-33 Display grids as block in print

- src/nice.bootstrap/_forms.scss
https://nicedigital.atlassian.net/browse/NOC-36
> NOC-36 Global nav styling conflict

- package-lock.json
- package.json
- src/layout/_grid-custom.scss
- src/nice.bootstrap/_grid.scss
- src/nice.bootstrap/_media-list.scss
- src/nice.bootstrap/navigation/_nav-grid.scss
- src/nice.bootstrap/navigation/_nav.scss
https://nicedigital.atlassian.net/browse/NOC-39
> NOC-39 Update NDS version

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-41
> NOC-41 Bump NDS to 1.2.4

- .vscode/settings.json
- package-lock.json
- package.json
- src/scss/_noc-colours.scss
- src/scss/nice.bootstrap/_media.scss
- src/scss/nice.bootstrap/_page-header.scss
- src/scss/nice.bootstrap/_thumbnail.scss
https://nicedigital.atlassian.net/browse/NOC-55
> NOC-55 Brand release snagging list

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-56
https://nicedigital.atlassian.net/browse/NOC-57
> NOC-56; NOC-57 Bump design system version

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-59
> NOC-59 Update NDS version to change button colour

- .prettierignore
- server/playground.ejs
- src/scss/components/_index.scss
- src/scss/components/_trac-feed.scss
- src/scss/layout/_container.scss
https://nicedigital.atlassian.net/browse/NOC-58
> NOC-58 Styling of trac jobs feed

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-60
> NOC-60 Update NDS to latest version

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/NOC-61
> NOC-61 Bump NDS version
